.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie5 - Debug ]----------"
	@cd "zadanie5" && "$(MAKE)" -f  "zadanie5.mk"
clean:
	@echo "----------Cleaning project:[ zadanie5 - Debug ]----------"
	@cd "zadanie5" && "$(MAKE)" -f  "zadanie5.mk" clean
